CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory"
(
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE "AspNetRoles"
(
    "Id"               uuid NOT NULL,
    "Name"             character varying(256),
    "NormalizedName"   character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers"
(
    "Id"                   uuid                     NOT NULL,
    "FullName"             text,
    "Status"               text                     NOT NULL,
    "CreatedAt"            timestamp with time zone NOT NULL,
    "UpdatedAt"            timestamp with time zone,
    "PhoneNumber"          text,
    "OtpCode"              text,
    "OtpExpiredAt"         timestamp with time zone,
    "BuyerType"            text,
    "UserName"             character varying(256),
    "NormalizedUserName"   character varying(256),
    "Email"                character varying(256),
    "NormalizedEmail"      character varying(256),
    "EmailConfirmed"       boolean                  NOT NULL,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumberConfirmed" boolean                  NOT NULL,
    "TwoFactorEnabled"     boolean                  NOT NULL,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean                  NOT NULL,
    "AccessFailedCount"    integer                  NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "PaymentPackages"
(
    "PackageId"        uuid           NOT NULL,
    "Name"             text           NOT NULL,
    "Description"      text,
    "Price"            numeric(18, 2) NOT NULL,
    "ConnectionAmount" integer,
    "IsActive"         boolean        NOT NULL,
    "PackageType"      text           NOT NULL,
    CONSTRAINT "PK_PaymentPackages" PRIMARY KEY ("PackageId")
);

CREATE TABLE "Ranks"
(
    "RankId"        integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"          character varying(50) NOT NULL,
    "MinPoints"     integer               NOT NULL,
    "BadgeImageUrl" text,
    CONSTRAINT "PK_Ranks" PRIMARY KEY ("RankId")
);

CREATE TABLE "RewardItems"
(
    "RewardItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ItemName"     character varying(150) NOT NULL,
    "Description"  text,
    "PointsCost"   integer                NOT NULL,
    "ImageUrl"     text,
    "Type"         text                   NOT NULL,
    "Value"        text                   NOT NULL,
    CONSTRAINT "PK_RewardItems" PRIMARY KEY ("RewardItemId")
);

CREATE TABLE "ScrapCategories"
(
    "ScrapCategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName"    character varying(100) NOT NULL,
    "Description"     text,
    CONSTRAINT "PK_ScrapCategories" PRIMARY KEY ("ScrapCategoryId")
);

CREATE TABLE "AspNetRoleClaims"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId"     uuid NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"     uuid NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins"
(
    "LoginProvider"       text NOT NULL,
    "ProviderKey"         text NOT NULL,
    "ProviderDisplayName" text,
    "UserId"              uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles"
(
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens"
(
    "UserId"        uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CollectorVerificationInfos"
(
    "UserId"         uuid NOT NULL,
    "Status"         text NOT NULL,
    "IdentityNumber" character varying(50),
    "FullnameOnId"   character varying(100),
    "DateOfBirth"    timestamp with time zone,
    "PlaceOfOrigin"  character varying(255),
    "IssuedBy"       character varying(200),
    "IssuedDate"     timestamp with time zone,
    "SubmittedAt"    timestamp with time zone,
    "ReviewerId"     uuid,
    "ReviewedAt"     timestamp with time zone,
    "ReviewerNotes"  character varying(500),
    CONSTRAINT "PK_CollectorVerificationInfos" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_CollectorVerificationInfos_AspNetUsers_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CollectorVerificationInfos_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CreditTransactionHistory"
(
    "Id"           uuid                     NOT NULL,
    "UserId"       uuid                     NOT NULL,
    "Amount"       integer                  NOT NULL,
    "BalanceAfter" integer                  NOT NULL,
    "Type"         character varying(50)    NOT NULL,
    "ReferenceId"  uuid,
    "Description"  character varying(255),
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_CreditTransactionHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CreditTransactionHistory_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications"
(
    "NotificationId" uuid                     NOT NULL,
    "RecipientId"    uuid                     NOT NULL,
    "Content"        text                     NOT NULL,
    "IsRead"         boolean                  NOT NULL DEFAULT FALSE,
    "CreatedAt"      timestamp with time zone NOT NULL,
    "EntityType"     character varying(50),
    "EntityId"       uuid,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId"),
    CONSTRAINT "FK_Notifications_AspNetUsers_RecipientId" FOREIGN KEY ("RecipientId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PointHistories"
(
    "PointHistoryId" uuid                     NOT NULL,
    "UserId"         uuid                     NOT NULL,
    "PointChange"    integer                  NOT NULL,
    "Reason"         character varying(255)   NOT NULL,
    "CreatedAt"      timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointHistories" PRIMARY KEY ("PointHistoryId"),
    CONSTRAINT "FK_PointHistories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScrapPosts"
(
    "ScrapPostId"        uuid                     NOT NULL,
    "HouseholdId"        uuid                     NOT NULL,
    "Title"              character varying(200)   NOT NULL,
    "Description"        text,
    "Address"            character varying(255)   NOT NULL,
    "AvailableTimeRange" character varying(100),
    "Status"             text                     NOT NULL,
    "CreatedAt"          timestamp with time zone NOT NULL,
    "UpdatedAt"          timestamp with time zone,
    "Location"           geometry(Point, 4326),
    "MustTakeAll"        boolean                  NOT NULL,
    CONSTRAINT "PK_ScrapPosts" PRIMARY KEY ("ScrapPostId"),
    CONSTRAINT "FK_ScrapPosts_AspNetUsers_HouseholdId" FOREIGN KEY ("HouseholdId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserDevices"
(
    "DeviceId"    uuid                     NOT NULL,
    "UserId"      uuid                     NOT NULL,
    "FcmToken"    text                     NOT NULL,
    "Platform"    text,
    "LastUpdated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserDevices" PRIMARY KEY ("DeviceId"),
    CONSTRAINT "FK_UserDevices_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PaymentTransactions"
(
    "PaymentId"        uuid                     NOT NULL,
    "UserId"           uuid                     NOT NULL,
    "PackageId"        uuid,
    "Amount"           numeric(18, 2)           NOT NULL,
    "PaymentGateway"   text                     NOT NULL,
    "Status"           text                     NOT NULL,
    "TransactionRef"   character varying(100),
    "VnpTransactionNo" character varying(100),
    "BankCode"         text,
    "ResponseCode"     text,
    "OrderInfo"        text,
    "ClientIpAddress"  text,
    "CreatedAt"        timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("PaymentId"),
    CONSTRAINT "FK_PaymentTransactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentTransactions_PaymentPackages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "PaymentPackages" ("PackageId")
);

CREATE TABLE "UserPackages"
(
    "UserPackageId"        uuid                     NOT NULL,
    "UserId"               uuid                     NOT NULL,
    "PackageId"            uuid                     NOT NULL,
    "ActivationDate"       timestamp with time zone NOT NULL,
    "ExpirationDate"       timestamp with time zone,
    "RemainingConnections" integer,
    CONSTRAINT "PK_UserPackages" PRIMARY KEY ("UserPackageId"),
    CONSTRAINT "FK_UserPackages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPackages_PaymentPackages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "PaymentPackages" ("PackageId") ON DELETE CASCADE
);

CREATE TABLE "Profiles"
(
    "ProfileId"         uuid    NOT NULL,
    "UserId"            uuid    NOT NULL,
    "DateOfBirth"       date,
    "Address"           character varying(255),
    "Gender"            text,
    "AvatarUrl"         text,
    "PointBalance"      integer NOT NULL DEFAULT 200,
    "RankId"            integer NOT NULL,
    "Location"          geometry(Point, 4326),
    "BankCode"          character varying(20),
    "BankAccountNumber" character varying(50),
    "BankAccountName"   character varying(100),
    "CreditBalance"     integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("ProfileId"),
    CONSTRAINT "FK_Profiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Profiles_Ranks_RankId" FOREIGN KEY ("RankId") REFERENCES "Ranks" ("RankId") ON DELETE CASCADE
);

CREATE TABLE "UserRewardRedemptions"
(
    "UserId"         uuid                     NOT NULL,
    "RewardItemId"   integer                  NOT NULL,
    "RedemptionDate" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_UserRewardRedemptions" PRIMARY KEY ("UserId", "RewardItemId", "RedemptionDate"),
    CONSTRAINT "FK_UserRewardRedemptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRewardRedemptions_RewardItems_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "RewardItems" ("RewardItemId") ON DELETE CASCADE
);

CREATE TABLE "ReferencePrices"
(
    "ReferencePriceId" uuid                     NOT NULL,
    "ScrapCategoryId"  integer                  NOT NULL,
    "PricePerKg"       numeric(18, 2)           NOT NULL,
    "LastUpdated"      timestamp with time zone NOT NULL,
    "UpdatedByAdminId" uuid                     NOT NULL,
    CONSTRAINT "PK_ReferencePrices" PRIMARY KEY ("ReferencePriceId"),
    CONSTRAINT "FK_ReferencePrices_AspNetUsers_UpdatedByAdminId" FOREIGN KEY ("UpdatedByAdminId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ReferencePrices_ScrapCategories_ScrapCategoryId" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE CASCADE
);

CREATE TABLE "CollectionOffers"
(
    "CollectionOfferId" uuid                     NOT NULL,
    "ScrapPostId"       uuid                     NOT NULL,
    "ScrapCollectorId"  uuid                     NOT NULL,
    "Status"            text                     NOT NULL,
    "CreatedAt"         timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CollectionOffers" PRIMARY KEY ("CollectionOfferId"),
    CONSTRAINT "FK_CollectionOffers_AspNetUsers_ScrapCollectorId" FOREIGN KEY ("ScrapCollectorId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CollectionOffers_ScrapPosts_ScrapPostId" FOREIGN KEY ("ScrapPostId") REFERENCES "ScrapPosts" ("ScrapPostId") ON DELETE CASCADE
);

CREATE TABLE "ScrapPostDetails"
(
    "ScrapPostId"       uuid    NOT NULL,
    "ScrapCategoryId"   integer NOT NULL,
    "AmountDescription" character varying(100),
    "ImageUrl"          text,
    "Status"            text    NOT NULL,
    CONSTRAINT "PK_ScrapPostDetails" PRIMARY KEY ("ScrapPostId", "ScrapCategoryId"),
    CONSTRAINT "FK_ScrapPostDetails_ScrapCategories_ScrapCategoryId" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE CASCADE,
    CONSTRAINT "FK_ScrapPostDetails_ScrapPosts_ScrapPostId" FOREIGN KEY ("ScrapPostId") REFERENCES "ScrapPosts" ("ScrapPostId") ON DELETE CASCADE
);

CREATE TABLE "OfferDetail"
(
    "OfferDetailId"     uuid                  NOT NULL,
    "CollectionOfferId" uuid                  NOT NULL,
    "ScrapCategoryId"   integer               NOT NULL,
    "PricePerUnit"      numeric(18, 2)        NOT NULL,
    "Unit"              character varying(10) NOT NULL DEFAULT 'kg',
    CONSTRAINT "PK_OfferDetail" PRIMARY KEY ("OfferDetailId"),
    CONSTRAINT "FK_OfferDetail_CollectionOffers_CollectionOfferId" FOREIGN KEY ("CollectionOfferId") REFERENCES "CollectionOffers" ("CollectionOfferId") ON DELETE CASCADE,
    CONSTRAINT "FK_OfferDetail_ScrapCategories_ScrapCategoryId" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE RESTRICT
);

CREATE TABLE "ScheduleProposals"
(
    "ScheduleProposalId" uuid                     NOT NULL,
    "CollectionOfferId"  uuid                     NOT NULL,
    "ProposerId"         uuid                     NOT NULL,
    "ProposedTime"       timestamp with time zone NOT NULL,
    "Status"             text                     NOT NULL,
    "CreatedAt"          timestamp with time zone NOT NULL,
    "ResponseMessage"    text,
    CONSTRAINT "PK_ScheduleProposals" PRIMARY KEY ("ScheduleProposalId"),
    CONSTRAINT "FK_ScheduleProposals_AspNetUsers_ProposerId" FOREIGN KEY ("ProposerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScheduleProposals_CollectionOffers_CollectionOfferId" FOREIGN KEY ("CollectionOfferId") REFERENCES "CollectionOffers" ("CollectionOfferId") ON DELETE CASCADE
);

CREATE TABLE "Transactions"
(
    "TransactionId"    uuid                     NOT NULL,
    "HouseholdId"      uuid                     NOT NULL,
    "ScrapCollectorId" uuid                     NOT NULL,
    "OfferId"          uuid                     NOT NULL,
    "Status"           text                     NOT NULL,
    "PaymentMethod"    text,
    "TotalAmount"      numeric(18, 2)           NOT NULL,
    "ScheduledTime"    timestamp with time zone,
    "CheckInTime"      timestamp with time zone,
    "CheckInLocation"  geometry(Point, 4326),
    "CreatedAt"        timestamp with time zone NOT NULL,
    "UpdatedAt"        timestamp with time zone,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("TransactionId"),
    CONSTRAINT "FK_Transactions_AspNetUsers_HouseholdId" FOREIGN KEY ("HouseholdId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Transactions_AspNetUsers_ScrapCollectorId" FOREIGN KEY ("ScrapCollectorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Transactions_CollectionOffers_OfferId" FOREIGN KEY ("OfferId") REFERENCES "CollectionOffers" ("CollectionOfferId") ON DELETE RESTRICT
);

CREATE TABLE "ChatRooms"
(
    "ChatRoomId"    uuid                     NOT NULL,
    "TransactionId" uuid                     NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatRooms" PRIMARY KEY ("ChatRoomId"),
    CONSTRAINT "FK_ChatRooms_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "Complaints"
(
    "ComplaintId"   uuid                     NOT NULL,
    "TransactionId" uuid                     NOT NULL,
    "ComplainantId" uuid                     NOT NULL,
    "AccusedId"     uuid                     NOT NULL,
    "Reason"        text                     NOT NULL,
    "EvidenceUrl"   text,
    "Status"        text                     NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Complaints" PRIMARY KEY ("ComplaintId"),
    CONSTRAINT "FK_Complaints_AspNetUsers_AccusedId" FOREIGN KEY ("AccusedId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Complaints_AspNetUsers_ComplainantId" FOREIGN KEY ("ComplainantId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Complaints_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "Feedbacks"
(
    "FeedbackId"    uuid                     NOT NULL,
    "TransactionId" uuid                     NOT NULL,
    "ReviewerId"    uuid                     NOT NULL,
    "RevieweeId"    uuid                     NOT NULL,
    "Rate"          integer                  NOT NULL,
    "Comment"       text,
    "CreatedAt"     timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("FeedbackId"),
    CONSTRAINT "FK_Feedbacks_AspNetUsers_RevieweeId" FOREIGN KEY ("RevieweeId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Feedbacks_AspNetUsers_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Feedbacks_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "TransactionDetails"
(
    "TransactionId"   uuid                  NOT NULL,
    "ScrapCategoryId" integer               NOT NULL,
    "PricePerUnit"    numeric(18, 2)        NOT NULL,
    "Unit"            character varying(10) NOT NULL DEFAULT 'kg',
    "Quantity"        real                  NOT NULL,
    "FinalPrice"      numeric(18, 2)        NOT NULL,
    CONSTRAINT "PK_TransactionDetails" PRIMARY KEY ("TransactionId", "ScrapCategoryId"),
    CONSTRAINT "FK_TransactionDetails_ScrapCategories_ScrapCategoryId" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE RESTRICT,
    CONSTRAINT "FK_TransactionDetails_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "ChatParticipants"
(
    "UserId"     uuid                     NOT NULL,
    "ChatRoomId" uuid                     NOT NULL,
    "JoinedAt"   timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_ChatParticipants" PRIMARY KEY ("UserId", "ChatRoomId"),
    CONSTRAINT "FK_ChatParticipants_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatParticipants_ChatRooms_ChatRoomId" FOREIGN KEY ("ChatRoomId") REFERENCES "ChatRooms" ("ChatRoomId") ON DELETE CASCADE
);

CREATE TABLE "Messages"
(
    "MessageId"  uuid                     NOT NULL,
    "ChatRoomId" uuid                     NOT NULL,
    "SenderId"   uuid                     NOT NULL,
    "Content"    text                     NOT NULL,
    "IsRead"     boolean                  NOT NULL,
    "Timestamp"  timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_Messages_AspNetUsers_SenderId" FOREIGN KEY ("SenderId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_ChatRooms_ChatRoomId" FOREIGN KEY ("ChatRoomId") REFERENCES "ChatRooms" ("ChatRoomId") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_ChatParticipants_ChatRoomId" ON "ChatParticipants" ("ChatRoomId");

CREATE UNIQUE INDEX "IX_ChatRooms_TransactionId" ON "ChatRooms" ("TransactionId");

CREATE INDEX "IX_CollectionOffers_ScrapCollectorId" ON "CollectionOffers" ("ScrapCollectorId");

CREATE INDEX "IX_CollectionOffers_ScrapPostId" ON "CollectionOffers" ("ScrapPostId");

CREATE UNIQUE INDEX "IX_CollectorVerificationInfos_IdentityNumber" ON "CollectorVerificationInfos" ("IdentityNumber");

CREATE INDEX "IX_CollectorVerificationInfos_ReviewerId" ON "CollectorVerificationInfos" ("ReviewerId");

CREATE INDEX "IX_CollectorVerificationInfos_Status" ON "CollectorVerificationInfos" ("Status");

CREATE INDEX "IX_Complaints_AccusedId" ON "Complaints" ("AccusedId");

CREATE INDEX "IX_Complaints_ComplainantId" ON "Complaints" ("ComplainantId");

CREATE INDEX "IX_Complaints_TransactionId" ON "Complaints" ("TransactionId");

CREATE INDEX "IX_CreditTransactionHistory_UserId" ON "CreditTransactionHistory" ("UserId");

CREATE INDEX "IX_Feedbacks_RevieweeId" ON "Feedbacks" ("RevieweeId");

CREATE INDEX "IX_Feedbacks_ReviewerId" ON "Feedbacks" ("ReviewerId");

CREATE INDEX "IX_Feedbacks_TransactionId" ON "Feedbacks" ("TransactionId");

CREATE INDEX "IX_Messages_ChatRoomId_Timestamp" ON "Messages" ("ChatRoomId", "Timestamp" DESC);

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Notifications_RecipientId_CreatedAt" ON "Notifications" ("RecipientId", "CreatedAt" DESC);

CREATE INDEX "IX_OfferDetail_CollectionOfferId" ON "OfferDetail" ("CollectionOfferId");

CREATE INDEX "IX_OfferDetail_ScrapCategoryId" ON "OfferDetail" ("ScrapCategoryId");

CREATE INDEX "IX_PaymentTransactions_PackageId" ON "PaymentTransactions" ("PackageId");

CREATE INDEX "IX_PaymentTransactions_UserId" ON "PaymentTransactions" ("UserId");

CREATE INDEX "IX_PointHistories_UserId" ON "PointHistories" ("UserId");

CREATE INDEX "IX_Profiles_Location" ON "Profiles" USING gist ("Location");

CREATE INDEX "IX_Profiles_RankId" ON "Profiles" ("RankId");

CREATE UNIQUE INDEX "IX_Profiles_UserId" ON "Profiles" ("UserId");

CREATE UNIQUE INDEX "IX_Ranks_MinPoints" ON "Ranks" ("MinPoints");

CREATE INDEX "IX_ReferencePrices_ScrapCategoryId" ON "ReferencePrices" ("ScrapCategoryId");

CREATE INDEX "IX_ReferencePrices_UpdatedByAdminId" ON "ReferencePrices" ("UpdatedByAdminId");

CREATE INDEX "IX_ScheduleProposals_CollectionOfferId" ON "ScheduleProposals" ("CollectionOfferId");

CREATE INDEX "IX_ScheduleProposals_ProposerId" ON "ScheduleProposals" ("ProposerId");

CREATE INDEX "IX_ScrapPostDetails_ScrapCategoryId" ON "ScrapPostDetails" ("ScrapCategoryId");

CREATE INDEX "IX_ScrapPosts_HouseholdId" ON "ScrapPosts" ("HouseholdId");

CREATE INDEX "IX_ScrapPosts_Location" ON "ScrapPosts" USING gist ("Location");

CREATE INDEX "IX_ScrapPosts_Status_HouseholdId" ON "ScrapPosts" ("Status", "HouseholdId");

CREATE INDEX "IX_TransactionDetails_ScrapCategoryId" ON "TransactionDetails" ("ScrapCategoryId");

CREATE INDEX "IX_Transactions_HouseholdId" ON "Transactions" ("HouseholdId");

CREATE INDEX "IX_Transactions_OfferId" ON "Transactions" ("OfferId");

CREATE INDEX "IX_Transactions_ScrapCollectorId" ON "Transactions" ("ScrapCollectorId");

CREATE UNIQUE INDEX "IX_UserDevices_FcmToken" ON "UserDevices" ("FcmToken");

CREATE INDEX "IX_UserDevices_UserId" ON "UserDevices" ("UserId");

CREATE INDEX "IX_UserPackages_PackageId" ON "UserPackages" ("PackageId");

CREATE INDEX "IX_UserPackages_UserId" ON "UserPackages" ("UserId");

CREATE INDEX "IX_UserRewardRedemptions_RewardItemId" ON "UserRewardRedemptions" ("RewardItemId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251205182117_Initial_Database', '9.0.9');

COMMIT;

