CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "FullName" text,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "PhoneNumber" text,
    "OtpCode" text,
    "OtpExpiredAt" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "RewardItems" (
    "RewardItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ItemName" character varying(150) NOT NULL,
    "Description" text,
    "PointsCost" integer NOT NULL,
    CONSTRAINT "RewardItems_pkey" PRIMARY KEY ("RewardItemId")
);

CREATE TABLE "ScrapCategories" (
    "ScrapCategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" character varying(100) NOT NULL,
    "Description" text,
    CONSTRAINT "ScrapCategories_pkey" PRIMARY KEY ("ScrapCategoryId")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CollectorVerificationInfos" (
    "UserId" uuid NOT NULL,
    "Status" text NOT NULL,
    "DocumentFrontUrl" text,
    "DocumentBackUrl" text,
    "SubmittedAt" timestamp with time zone,
    "ReviewerId" uuid,
    "ReviewedAt" timestamp with time zone,
    "ReviewerNotes" text,
    CONSTRAINT "CollectorVerificationInfos_pkey" PRIMARY KEY ("UserId"),
    CONSTRAINT "CollectorVerificationInfos_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CollectorVerificationInfos_AspNetUsers_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Notifications" (
    "NotificationId" uuid NOT NULL,
    "RecipientId" uuid NOT NULL,
    "Content" text NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "EntityType" character varying(50),
    "EntityId" uuid,
    CONSTRAINT "Notifications_pkey" PRIMARY KEY ("NotificationId"),
    CONSTRAINT "Notifications_RecipientId_fkey" FOREIGN KEY ("RecipientId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Profiles" (
    "ProfileId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "DateOfBirth" date,
    "Address" character varying(255),
    "Gender" character varying(10),
    "AvatarUrl" text,
    "RewardPoint" integer NOT NULL DEFAULT 0,
    "Location" geometry(Point,4326),
    CONSTRAINT "Profiles_pkey" PRIMARY KEY ("ProfileId"),
    CONSTRAINT "Profiles_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScrapPosts" (
    "ScrapPostId" uuid NOT NULL,
    "HouseholdId" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "Address" character varying(255) NOT NULL,
    "AvailableTimeRange" character varying(100),
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone,
    "Location" geometry(Point,4326),
    CONSTRAINT "ScrapPosts_pkey" PRIMARY KEY ("ScrapPostId"),
    CONSTRAINT "ScrapPosts_HouseholdId_fkey" FOREIGN KEY ("HouseholdId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRewardRedemptions" (
    "UserId" uuid NOT NULL,
    "RewardItemId" integer NOT NULL,
    "RedemptionDate" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "UserRewardRedemptions_pkey" PRIMARY KEY ("UserId", "RewardItemId", "RedemptionDate"),
    CONSTRAINT "UserRewardRedemptions_RewardItemId_fkey" FOREIGN KEY ("RewardItemId") REFERENCES "RewardItems" ("RewardItemId") ON DELETE CASCADE,
    CONSTRAINT "UserRewardRedemptions_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CollectionOffers" (
    "CollectionOfferId" uuid NOT NULL,
    "ScrapPostId" uuid NOT NULL,
    "ScrapCollectorId" uuid NOT NULL,
    "ProposedPrice" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "CollectionOffers_pkey" PRIMARY KEY ("CollectionOfferId"),
    CONSTRAINT "CollectionOffers_ScrapCollectorId_fkey" FOREIGN KEY ("ScrapCollectorId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "CollectionOffers_ScrapPostId_fkey" FOREIGN KEY ("ScrapPostId") REFERENCES "ScrapPosts" ("ScrapPostId") ON DELETE CASCADE
);

CREATE TABLE "ScrapPostDetails" (
    "ScrapPostId" uuid NOT NULL,
    "ScrapCategoryId" integer NOT NULL,
    "AmountDescription" character varying(100),
    "ImageUrl" text,
    "Status" text NOT NULL,
    CONSTRAINT "ScrapPostDetails_pkey" PRIMARY KEY ("ScrapPostId", "ScrapCategoryId"),
    CONSTRAINT "ScrapPostDetails_ScrapCategoryId_fkey" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE CASCADE,
    CONSTRAINT "ScrapPostDetails_ScrapPostId_fkey" FOREIGN KEY ("ScrapPostId") REFERENCES "ScrapPosts" ("ScrapPostId") ON DELETE CASCADE
);

CREATE TABLE "Transactions" (
    "TransactionId" uuid NOT NULL,
    "HouseholdId" uuid NOT NULL,
    "ScrapCollectorId" uuid NOT NULL,
    "OfferId" uuid NOT NULL,
    "Status" text NOT NULL,
    "ScheduledTime" timestamp with time zone,
    "CheckInTime" timestamp with time zone,
    "CheckInSelfieUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "Transactions_pkey" PRIMARY KEY ("TransactionId"),
    CONSTRAINT "Transactions_HouseholdId_fkey" FOREIGN KEY ("HouseholdId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "Transactions_OfferId_fkey" FOREIGN KEY ("OfferId") REFERENCES "CollectionOffers" ("CollectionOfferId") ON DELETE RESTRICT,
    CONSTRAINT "Transactions_ScrapCollectorId_fkey" FOREIGN KEY ("ScrapCollectorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CollectionOfferScrapPostDetail" (
    "CollectionOffersCollectionOfferId" uuid NOT NULL,
    "ScrapPostDetailsScrapPostId" uuid NOT NULL,
    "ScrapPostDetailsScrapCategoryId" integer NOT NULL,
    CONSTRAINT "PK_CollectionOfferScrapPostDetail" PRIMARY KEY ("CollectionOffersCollectionOfferId", "ScrapPostDetailsScrapPostId", "ScrapPostDetailsScrapCategoryId"),
    CONSTRAINT "FK_CollectionOfferScrapPostDetail_CollectionOffers_CollectionO~" FOREIGN KEY ("CollectionOffersCollectionOfferId") REFERENCES "CollectionOffers" ("CollectionOfferId") ON DELETE CASCADE,
    CONSTRAINT "FK_CollectionOfferScrapPostDetail_ScrapPostDetails_ScrapPostDe~" FOREIGN KEY ("ScrapPostDetailsScrapPostId", "ScrapPostDetailsScrapCategoryId") REFERENCES "ScrapPostDetails" ("ScrapPostId", "ScrapCategoryId") ON DELETE CASCADE
);

CREATE TABLE "ChatRooms" (
    "ChatRoomId" uuid NOT NULL,
    "TransactionId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "ChatRooms_pkey" PRIMARY KEY ("ChatRoomId"),
    CONSTRAINT "ChatRooms_TransactionId_fkey" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "Complaints" (
    "ComplaintId" uuid NOT NULL,
    "TransactionId" uuid NOT NULL,
    "ComplainantId" uuid NOT NULL,
    "AccusedId" uuid NOT NULL,
    "Reason" text NOT NULL,
    "EvidenceUrl" text,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "Complaints_pkey" PRIMARY KEY ("ComplaintId"),
    CONSTRAINT "Complaints_AccusedId_fkey" FOREIGN KEY ("AccusedId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "Complaints_ComplainantId_fkey" FOREIGN KEY ("ComplainantId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "Complaints_TransactionId_fkey" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "Feedbacks" (
    "FeedbackId" uuid NOT NULL,
    "TransactionId" uuid NOT NULL,
    "ReviewerId" uuid NOT NULL,
    "RevieweeId" uuid NOT NULL,
    "Rate" integer NOT NULL,
    "Comment" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "Feedbacks_pkey" PRIMARY KEY ("FeedbackId"),
    CONSTRAINT "Feedbacks_RevieweeId_fkey" FOREIGN KEY ("RevieweeId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "Feedbacks_ReviewerId_fkey" FOREIGN KEY ("ReviewerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "Feedbacks_TransactionId_fkey" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "ScheduleProposals" (
    "ScheduleProposalId" uuid NOT NULL,
    "TransactionId" uuid NOT NULL,
    "ProposerId" uuid NOT NULL,
    "ProposedTime" timestamp with time zone NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "ResponseMessage" text,
    CONSTRAINT "ScheduleProposals_pkey" PRIMARY KEY ("ScheduleProposalId"),
    CONSTRAINT "ScheduleProposals_ProposerId_fkey" FOREIGN KEY ("ProposerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "ScheduleProposals_TransactionId_fkey" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "TransactionDetails" (
    "TransactionId" uuid NOT NULL,
    "ScrapCategoryId" integer NOT NULL,
    "ActualWeight" real NOT NULL,
    "ActualPrice" numeric(18,2) NOT NULL,
    CONSTRAINT "TransactionDetails_pkey" PRIMARY KEY ("TransactionId", "ScrapCategoryId"),
    CONSTRAINT "TransactionDetails_ScrapCategoryId_fkey" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE RESTRICT,
    CONSTRAINT "TransactionDetails_TransactionId_fkey" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("TransactionId") ON DELETE CASCADE
);

CREATE TABLE "ChatParticipants" (
    "UserId" uuid NOT NULL,
    "ChatRoomId" uuid NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "ChatParticipants_pkey" PRIMARY KEY ("UserId", "ChatRoomId"),
    CONSTRAINT "ChatParticipants_ChatRoomId_fkey" FOREIGN KEY ("ChatRoomId") REFERENCES "ChatRooms" ("ChatRoomId") ON DELETE CASCADE,
    CONSTRAINT "ChatParticipants_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "MessageId" uuid NOT NULL,
    "ChatRoomId" uuid NOT NULL,
    "SenderId" uuid NOT NULL,
    "Content" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "Messages_pkey" PRIMARY KEY ("MessageId"),
    CONSTRAINT "Messages_ChatRoomId_fkey" FOREIGN KEY ("ChatRoomId") REFERENCES "ChatRooms" ("ChatRoomId") ON DELETE CASCADE,
    CONSTRAINT "Messages_SenderId_fkey" FOREIGN KEY ("SenderId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_ChatParticipants_ChatRoomId" ON "ChatParticipants" ("ChatRoomId");

CREATE UNIQUE INDEX "ChatRooms_TransactionId_key" ON "ChatRooms" ("TransactionId");

CREATE INDEX "IX_CollectionOffers_ScrapCollectorId" ON "CollectionOffers" ("ScrapCollectorId");

CREATE INDEX "IX_CollectionOffers_ScrapPostId" ON "CollectionOffers" ("ScrapPostId");

CREATE INDEX "IX_CollectionOfferScrapPostDetail_ScrapPostDetailsScrapPostId_~" ON "CollectionOfferScrapPostDetail" ("ScrapPostDetailsScrapPostId", "ScrapPostDetailsScrapCategoryId");

CREATE INDEX "IX_CollectorVerificationInfos_ReviewerId" ON "CollectorVerificationInfos" ("ReviewerId");

CREATE INDEX "IX_Complaints_AccusedId" ON "Complaints" ("AccusedId");

CREATE INDEX "IX_Complaints_ComplainantId" ON "Complaints" ("ComplainantId");

CREATE INDEX "IX_Complaints_TransactionId" ON "Complaints" ("TransactionId");

CREATE INDEX "IX_Feedbacks_RevieweeId" ON "Feedbacks" ("RevieweeId");

CREATE INDEX "IX_Feedbacks_ReviewerId" ON "Feedbacks" ("ReviewerId");

CREATE INDEX "IX_Feedbacks_TransactionId" ON "Feedbacks" ("TransactionId");

CREATE INDEX "IX_Messages_ChatRoomId_Timestamp" ON "Messages" ("ChatRoomId", "Timestamp" DESC);

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Notifications_RecipientId_CreatedAt" ON "Notifications" ("RecipientId", "CreatedAt" DESC);

CREATE INDEX "IX_Profiles_Location" ON "Profiles" USING gist ("Location");

CREATE UNIQUE INDEX "Profiles_UserId_key" ON "Profiles" ("UserId");

CREATE INDEX "IX_ScheduleProposals_ProposerId" ON "ScheduleProposals" ("ProposerId");

CREATE INDEX "IX_ScheduleProposals_TransactionId" ON "ScheduleProposals" ("TransactionId");

CREATE INDEX "IX_ScrapPostDetails_ScrapCategoryId" ON "ScrapPostDetails" ("ScrapCategoryId");

CREATE INDEX "IX_ScrapPosts_HouseholdId" ON "ScrapPosts" ("HouseholdId");

CREATE INDEX "IX_ScrapPosts_Location" ON "ScrapPosts" USING gist ("Location");

CREATE INDEX "IX_ScrapPosts_Status_HouseholdId" ON "ScrapPosts" ("Status", "HouseholdId");

CREATE INDEX "IX_TransactionDetails_ScrapCategoryId" ON "TransactionDetails" ("ScrapCategoryId");

CREATE INDEX "IX_Transactions_HouseholdId" ON "Transactions" ("HouseholdId");

CREATE INDEX "IX_Transactions_OfferId" ON "Transactions" ("OfferId");

CREATE INDEX "IX_Transactions_ScrapCollectorId" ON "Transactions" ("ScrapCollectorId");

CREATE INDEX "IX_Transactions_Status_HouseholdId" ON "Transactions" ("Status", "HouseholdId");

CREATE INDEX "IX_Transactions_Status_ScrapCollectorId" ON "Transactions" ("Status", "ScrapCollectorId");

CREATE INDEX "IX_UserRewardRedemptions_RewardItemId" ON "UserRewardRedemptions" ("RewardItemId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251015081535_InitialDatabase', '9.0.9');

ALTER TABLE "Transactions" DROP COLUMN "CheckInSelfieUrl";

ALTER TABLE "Profiles" DROP COLUMN "RewardPoint";

CREATE TYPE gender AS ENUM ('male', 'female', 'other');
CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE "Profiles" ALTER COLUMN "Gender" TYPE text;

ALTER TABLE "Profiles" ADD "PointBalance" integer NOT NULL DEFAULT 200;

ALTER TABLE "Profiles" ADD "RankId" integer NOT NULL DEFAULT 0;

ALTER TABLE "AspNetUsers" ADD "BuyerType" integer;

CREATE TABLE "PaymentPackages" (
    "PackageId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Price" numeric(18,2) NOT NULL,
    "ConnectionAmount" integer,
    "IsActive" boolean NOT NULL,
    "PackageType" integer NOT NULL,
    CONSTRAINT "PK_PaymentPackages" PRIMARY KEY ("PackageId")
);

CREATE TABLE "PointHistories" (
    "PointHistoryId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PointChange" integer NOT NULL,
    "Reason" character varying(255) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PointHistories" PRIMARY KEY ("PointHistoryId"),
    CONSTRAINT "FK_PointHistories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rank" (
    "RankId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "MinPoints" integer NOT NULL,
    "BadgeImageUrl" text,
    CONSTRAINT "PK_Rank" PRIMARY KEY ("RankId")
);

CREATE TABLE "ReferencePrices" (
    "ReferencePriceId" uuid NOT NULL,
    "ScrapCategoryId" integer NOT NULL,
    "PricePerKg" numeric(18,2) NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    "UpdatedByAdminId" uuid NOT NULL,
    CONSTRAINT "PK_ReferencePrices" PRIMARY KEY ("ReferencePriceId"),
    CONSTRAINT "FK_ReferencePrices_AspNetUsers_UpdatedByAdminId" FOREIGN KEY ("UpdatedByAdminId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ReferencePrices_ScrapCategories_ScrapCategoryId" FOREIGN KEY ("ScrapCategoryId") REFERENCES "ScrapCategories" ("ScrapCategoryId") ON DELETE CASCADE
);

CREATE TABLE "PaymentTransactions" (
    "PaymentId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PackageId" uuid,
    "Amount" numeric NOT NULL,
    "PaymentGateway" text NOT NULL,
    "TransactionCode" text,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("PaymentId"),
    CONSTRAINT "FK_PaymentTransactions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentTransactions_PaymentPackages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "PaymentPackages" ("PackageId")
);

CREATE TABLE "UserPackages" (
    "UserPackageId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PackageId" uuid NOT NULL,
    "ActivationDate" timestamp with time zone NOT NULL,
    "ExpirationDate" timestamp with time zone,
    "RemainingConnections" integer,
    CONSTRAINT "PK_UserPackages" PRIMARY KEY ("UserPackageId"),
    CONSTRAINT "FK_UserPackages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPackages_PaymentPackages_PackageId" FOREIGN KEY ("PackageId") REFERENCES "PaymentPackages" ("PackageId") ON DELETE CASCADE
);

CREATE INDEX "IX_Profiles_RankId" ON "Profiles" ("RankId");

CREATE INDEX "IX_PaymentTransactions_PackageId" ON "PaymentTransactions" ("PackageId");

CREATE INDEX "IX_PaymentTransactions_UserId" ON "PaymentTransactions" ("UserId");

CREATE INDEX "IX_PointHistories_UserId" ON "PointHistories" ("UserId");

CREATE UNIQUE INDEX "IX_Rank_MinPoints" ON "Rank" ("MinPoints");

CREATE INDEX "IX_ReferencePrices_ScrapCategoryId" ON "ReferencePrices" ("ScrapCategoryId");

CREATE INDEX "IX_ReferencePrices_UpdatedByAdminId" ON "ReferencePrices" ("UpdatedByAdminId");

CREATE INDEX "IX_UserPackages_PackageId" ON "UserPackages" ("PackageId");

CREATE INDEX "IX_UserPackages_UserId" ON "UserPackages" ("UserId");

ALTER TABLE "Profiles" ADD CONSTRAINT "FK_Profiles_Rank_RankId" FOREIGN KEY ("RankId") REFERENCES "Rank" ("RankId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251111151617_UpdateDatabase_AR2', '9.0.9');

COMMIT;

