// <auto-generated />
using System;
using GreenConnectPlatform.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenConnectPlatform.Data.Migrations
{
    [DbContext(typeof(GreenConnectDbContext))]
    partial class GreenConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatParticipant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "ChatRoomId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatParticipants");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            ChatRoomId = new Guid("2d68c33d-bd2e-4010-8aa1-1862301f5bde"),
                            JoinedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ChatRoomId = new Guid("2d68c33d-bd2e-4010-8aa1-1862301f5bde"),
                            JoinedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            ChatRoomId = new Guid("2d68c33d-bd2e-4010-8aa1-1862301f5bde"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScrapCollectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CollectionOfferId");

                    b.HasIndex("ScrapCollectorId");

                    b.HasIndex("ScrapPostId");

                    b.ToTable("CollectionOffers");

                    b.HasData(
                        new
                        {
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullnameOnId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlaceOfOrigin")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.HasIndex("ReviewerId");

                    b.HasIndex("Status");

                    b.ToTable("CollectorVerificationInfos");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullnameOnId = "NGUYEN VAN BA",
                            IdentityNumber = "079090000001",
                            IssuedBy = "Cục Cảnh sát QLHC về TTXH",
                            IssuedDate = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlaceOfOrigin = "TP.HCM",
                            Status = "PendingReview",
                            SubmittedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            FullnameOnId = "CONG TY TNHH VUA VE CHAI ABC",
                            IdentityNumber = "0312345678",
                            IssuedBy = "Sở Kế hoạch và Đầu tư TP.HCM",
                            IssuedDate = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            PlaceOfOrigin = "TP.HCM",
                            ReviewedAt = new DateTime(2025, 10, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReviewerId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            ReviewerNotes = "Giấy phép kinh doanh hợp lệ.",
                            Status = "Approved",
                            SubmittedAt = new DateTime(2025, 9, 30, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccusedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplainantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ComplaintId");

                    b.HasIndex("AccusedId");

                    b.HasIndex("ComplainantId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ComplaintId = new Guid("ca1d610f-1c1a-435e-a9e4-e1370cfa0bff"),
                            AccusedId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            ComplainantId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Hẹn không đến.",
                            Status = "Submitted",
                            TransactionId = new Guid("70000002-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CreditTransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditTransactionHistory");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("FeedbackId");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = new Guid("13996aef-c86c-422a-aa3b-eece73b13513"),
                            Comment = "Nhanh gọn lẹ.",
                            CreatedAt = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            Rate = 5,
                            RevieweeId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ReviewerId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ChatRoomId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = new Guid("1766e59d-a31b-4063-84aa-de32c33dd06d"),
                            ChatRoomId = new Guid("2d68c33d-bd2e-4010-8aa1-1862301f5bde"),
                            Content = "Chào chị, em tới rồi.",
                            IsRead = true,
                            SenderId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Timestamp = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MessageId = new Guid("3e460c78-f259-4d80-b300-8b228c3354b5"),
                            ChatRoomId = new Guid("2d68c33d-bd2e-4010-8aa1-1862301f5bde"),
                            Content = "Ok em.",
                            IsRead = true,
                            SenderId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Timestamp = new DateTime(2025, 10, 10, 12, 1, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = new Guid("a491f60c-b552-4e2f-9e0f-5591679d9586"),
                            Content = "Vựa ABC đã hoàn thành đơn hàng.",
                            CreatedAt = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("70000001-0000-0000-0000-000000000001"),
                            EntityType = "Transaction",
                            IsRead = false,
                            RecipientId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.OfferDetail", b =>
                {
                    b.Property<Guid>("OfferDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("kg");

                    b.HasKey("OfferDetailId");

                    b.HasIndex("CollectionOfferId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("OfferDetail");

                    b.HasData(
                        new
                        {
                            OfferDetailId = new Guid("bf87ccb4-5354-4922-8e1a-5a42fc0c0bc6"),
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            PricePerUnit = 3000m,
                            ScrapCategoryId = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            OfferDetailId = new Guid("5750de15-7d2a-4843-a19d-38a51e20c50b"),
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            PricePerUnit = 5000m,
                            ScrapCategoryId = 2,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConnectionAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("PackageId");

                    b.ToTable("PaymentPackages");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("a1111111-0000-0000-0000-000000000001"),
                            ConnectionAmount = 5,
                            Description = "5 lượt/tuần",
                            IsActive = true,
                            Name = "Gói Free",
                            PackageType = "Freemium",
                            Price = 0m
                        },
                        new
                        {
                            PackageId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            ConnectionAmount = 500,
                            Description = "500 lượt/tháng",
                            IsActive = true,
                            Name = "Gói Pro",
                            PackageType = "Paid",
                            Price = 200000m
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankCode")
                        .HasColumnType("text");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderInfo")
                        .HasColumnType("text");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VnpTransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("fa532179-a2ff-4b81-99a5-65990f0c74e8"),
                            Amount = 200000m,
                            BankCode = "NCB",
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderInfo = "Mua Goi Pro",
                            PackageId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            PaymentGateway = "VNPay",
                            ResponseCode = "00",
                            Status = "Success",
                            TransactionRef = "ORD001",
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            VnpTransactionNo = "VNP001"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PointHistory", b =>
                {
                    b.Property<Guid>("PointHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PointHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("PointHistories");

                    b.HasData(
                        new
                        {
                            PointHistoryId = new Guid("c6e421bb-9aae-494a-a3a4-f26c10c06d5b"),
                            CreatedAt = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = 10,
                            Reason = "Hoàn thành đơn",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            PointHistoryId = new Guid("05e0131e-6254-4401-a01a-62704e8a97ea"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = -20,
                            Reason = "Khiếu nại",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CreditBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<int>("PointBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(200);

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = new Guid("b6b12589-a56b-4eea-8395-3301b573d365"),
                            Address = "Headquarter",
                            CreditBalance = 0,
                            PointBalance = 9999,
                            RankId = 3,
                            UserId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ProfileId = new Guid("735f3054-5e66-4d6c-acee-3ff798776cfc"),
                            Address = "123 CMT8, Q3, HCM",
                            BankAccountName = "NGUYEN THI TU",
                            BankAccountNumber = "0922222222",
                            BankCode = "970422",
                            CreditBalance = 0,
                            Gender = "Female",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            PointBalance = 50,
                            RankId = 1,
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            ProfileId = new Guid("5bc5a760-22be-4c69-a2ac-3ad751ded537"),
                            Address = "Hẻm 456 Lê Văn Sỹ, Q3, HCM",
                            CreditBalance = 0,
                            Gender = "Male",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.68 10.78)"),
                            PointBalance = 120,
                            RankId = 1,
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00")
                        },
                        new
                        {
                            ProfileId = new Guid("03a7eae2-9222-423c-92bf-2a6c393df922"),
                            Address = "Kho Quận 7, HCM",
                            BankAccountName = "CTY ABC",
                            BankAccountNumber = "0988888888",
                            BankCode = "970436",
                            CreditBalance = 0,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.72 10.75)"),
                            PointBalance = 5000,
                            RankId = 2,
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankId"));

                    b.Property<string>("BadgeImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RankId");

                    b.HasIndex("MinPoints")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            RankId = 1,
                            BadgeImageUrl = "bronze.png",
                            MinPoints = 0,
                            Name = "Mới"
                        },
                        new
                        {
                            RankId = 2,
                            BadgeImageUrl = "silver.png",
                            MinPoints = 1000,
                            Name = "Bạc"
                        },
                        new
                        {
                            RankId = 3,
                            BadgeImageUrl = "gold.png",
                            MinPoints = 5000,
                            Name = "Vàng"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ReferencePrice", b =>
                {
                    b.Property<Guid>("ReferencePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferencePriceId");

                    b.HasIndex("ScrapCategoryId");

                    b.HasIndex("UpdatedByAdminId");

                    b.ToTable("ReferencePrices");

                    b.HasData(
                        new
                        {
                            ReferencePriceId = new Guid("33312e81-bb29-4714-b9e9-868260820fb7"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 3000m,
                            ScrapCategoryId = 1,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("9cb2c26f-d837-4466-ac59-d8d3b098fb6b"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 5000m,
                            ScrapCategoryId = 2,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("ed0fdf46-0ae8-46df-b506-c307d3b190de"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 15000m,
                            ScrapCategoryId = 3,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("3dc8324c-fc0c-4ed8-a2e8-ffe899b4ea87"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 8000m,
                            ScrapCategoryId = 4,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.RewardItem", b =>
                {
                    b.Property<int>("RewardItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RewardItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RewardItemId");

                    b.ToTable("RewardItems");

                    b.HasData(
                        new
                        {
                            RewardItemId = 1,
                            Description = "Đổi ngay 1 lượt xem SĐT để liên hệ chủ bài đăng.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_credit_1.png",
                            ItemName = "1 Lượt Kết Nối",
                            PointsCost = 100,
                            Type = "Credit",
                            Value = "1"
                        },
                        new
                        {
                            RewardItemId = 2,
                            Description = "Gói tiết kiệm. Phù hợp cho người thu gom thường xuyên.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_credit_5.png",
                            ItemName = "Combo 5 Lượt",
                            PointsCost = 450,
                            Type = "Credit",
                            Value = "5"
                        },
                        new
                        {
                            RewardItemId = 3,
                            Description = "Gói sỉ siêu hời. Thoải mái kết nối.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_credit_10.png",
                            ItemName = "Combo 10 Lượt",
                            PointsCost = 800,
                            Type = "Credit",
                            Value = "10"
                        },
                        new
                        {
                            RewardItemId = 4,
                            Description = "Mở khóa không giới hạn lượt xem và tính năng Pro trong 24h.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_vip_day.png",
                            ItemName = "Dùng thử VIP 1 Ngày",
                            PointsCost = 2000,
                            Type = "Package",
                            Value = "a2222222-0000-0000-0000-000000000001|1"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScheduleProposal", b =>
                {
                    b.Property<Guid>("ScheduleProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProposedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScheduleProposalId");

                    b.HasIndex("CollectionOfferId");

                    b.HasIndex("ProposerId");

                    b.ToTable("ScheduleProposals");

                    b.HasData(
                        new
                        {
                            ScheduleProposalId = new Guid("6d5e86d0-a338-417d-84d9-91167cb57df6"),
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProposedTime = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProposerId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ResponseMessage = "Ok chốt",
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapCategory", b =>
                {
                    b.Property<int>("ScrapCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScrapCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ScrapCategoryId");

                    b.ToTable("ScrapCategories");

                    b.HasData(
                        new
                        {
                            ScrapCategoryId = 1,
                            CategoryName = "Giấy / Carton"
                        },
                        new
                        {
                            ScrapCategoryId = 2,
                            CategoryName = "Nhựa (Chai/Lọ)"
                        },
                        new
                        {
                            ScrapCategoryId = 3,
                            CategoryName = "Lon Nhôm"
                        },
                        new
                        {
                            ScrapCategoryId = 4,
                            CategoryName = "Sắt vụn"
                        },
                        new
                        {
                            ScrapCategoryId = 5,
                            CategoryName = "Đồ điện tử"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvailableTimeRange")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<bool>("MustTakeAll")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScrapPostId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Status", "HouseholdId");

                    b.ToTable("ScrapPosts");

                    b.HasData(
                        new
                        {
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Address = "123 CMT8",
                            CreatedAt = new DateTime(2025, 10, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lấy hết giúp em.",
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            MustTakeAll = true,
                            Status = "Completed",
                            Title = "Dọn kho Giấy & Nhựa"
                        },
                        new
                        {
                            ScrapPostId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            Address = "123 CMT8",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ai tiện ghé lấy.",
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            MustTakeAll = false,
                            Status = "Open",
                            Title = "Bán 50 vỏ lon"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPostDetail", b =>
                {
                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("AmountDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScrapPostId", "ScrapCategoryId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("ScrapPostDetails");

                    b.HasData(
                        new
                        {
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 1,
                            AmountDescription = "20kg",
                            Status = "Collected"
                        },
                        new
                        {
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 2,
                            AmountDescription = "2 bao",
                            Status = "Collected"
                        },
                        new
                        {
                            ScrapPostId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 3,
                            AmountDescription = "50 lon",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Point>("CheckInLocation")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScrapCollectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ScrapCollectorId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001"),
                            CheckInLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            CheckInTime = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 5, 18, 21, 46, 298, DateTimeKind.Utc).AddTicks(9468),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            OfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            PaymentMethod = "Cash",
                            ScheduledTime = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Status = "Completed",
                            TotalAmount = 100000m
                        },
                        new
                        {
                            TransactionId = new Guid("70000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            OfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            ScrapCollectorId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            Status = "CanceledByUser",
                            TotalAmount = 0m
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.TransactionDetail", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("kg");

                    b.HasKey("TransactionId", "ScrapCategoryId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("TransactionDetails");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 1,
                            FinalPrice = 45000m,
                            PricePerUnit = 3000m,
                            Quantity = 15f,
                            Unit = "kg"
                        },
                        new
                        {
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 2,
                            FinalPrice = 55000m,
                            PricePerUnit = 5000m,
                            Quantity = 11f,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BuyerType")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fdf08af5-9ce5-4d6e-920e-8b41e88d1c6b",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gc.com",
                            EmailConfirmed = true,
                            FullName = "Admin System",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GC.COM",
                            NormalizedUserName = "0900000000",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0900000000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "97b2279c-b636-4bee-974d-d2e2d466179a",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0900000000"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d330eb9-648b-4e4e-865d-14888c664ac8",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chitu@gc.com",
                            EmailConfirmed = true,
                            FullName = "Chị Tư Nội Trợ",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHITU@GC.COM",
                            NormalizedUserName = "0922222222",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0922222222",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ef80a1d1-1d7f-45f3-8069-4003e7a7fafc",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0922222222"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            AccessFailedCount = 0,
                            BuyerType = "Individual",
                            ConcurrencyStamp = "5958c94f-4c83-4d40-be0f-9f4e0c891d06",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anhba@gc.com",
                            EmailConfirmed = true,
                            FullName = "Anh Ba Ve Chai",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANHBA@GC.COM",
                            NormalizedUserName = "0933333333",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0933333333",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "245da196-cbea-4e34-a751-47131b212434",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0933333333"
                        },
                        new
                        {
                            Id = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            AccessFailedCount = 0,
                            BuyerType = "Business",
                            ConcurrencyStamp = "873b01a7-9d5c-464a-984a-a8eca544e4bb",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuaabc@gc.com",
                            EmailConfirmed = true,
                            FullName = "Vựa Tái Chế ABC",
                            LockoutEnabled = false,
                            NormalizedEmail = "VUAABC@GC.COM",
                            NormalizedUserName = "0988888888",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0988888888",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c77d1192-4dd4-41e2-837e-dc9d79248431",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0988888888"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DeviceId");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserPackage", b =>
                {
                    b.Property<Guid>("UserPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingConnections")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPackageId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPackages");

                    b.HasData(
                        new
                        {
                            UserPackageId = new Guid("8d813450-e585-4ad2-8cae-5ba6fcfe1f58"),
                            ActivationDate = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("a1111111-0000-0000-0000-000000000001"),
                            RemainingConnections = 5,
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00")
                        },
                        new
                        {
                            UserPackageId = new Guid("f1162c19-279f-4328-b57b-c969a3680438"),
                            ActivationDate = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2025, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            RemainingConnections = 499,
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserRewardRedemption", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RedemptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RewardItemId", "RedemptionDate");

                    b.HasIndex("RewardItemId");

                    b.ToTable("UserRewardRedemptions");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            RewardItemId = 2,
                            RedemptionDate = new DateTime(2025, 10, 10, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dd3637c-72a3-4a25-99d2-a7d1bce85542"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f9e7c1b5-9c8f-4b1a-8c7d-6e5f4a3b2a1c"),
                            Name = "Household",
                            NormalizedName = "HOUSEHOLD"
                        },
                        new
                        {
                            Id = new Guid("d7d0c75c-9c3f-4e6b-9b7a-8f8d9a6c9e84"),
                            Name = "IndividualCollector",
                            NormalizedName = "INDIVIDUALCOLLECTOR"
                        },
                        new
                        {
                            Id = new Guid("e0a5a415-5a4e-4f6a-8b9a-1b2c3d4e5f6a"),
                            Name = "BusinessCollector",
                            NormalizedName = "BUSINESSCOLLECTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            RoleId = new Guid("8dd3637c-72a3-4a25-99d2-a7d1bce85542")
                        },
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            RoleId = new Guid("f9e7c1b5-9c8f-4b1a-8c7d-6e5f4a3b2a1c")
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            RoleId = new Guid("d7d0c75c-9c3f-4e6b-9b7a-8f8d9a6c9e84")
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            RoleId = new Guid("e0a5a415-5a4e-4f6a-8b9a-1b2c3d4e5f6a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatParticipant", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithOne("ChatRoom")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.ChatRoom", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "ScrapCollector")
                        .WithMany("CollectionOffers")
                        .HasForeignKey("ScrapCollectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapPost", "ScrapPost")
                        .WithMany("CollectionOffers")
                        .HasForeignKey("ScrapPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapCollector");

                    b.Navigation("ScrapPost");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithOne("CollectorVerificationInfo")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Complaint", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Accused")
                        .WithMany("ComplaintAccuseds")
                        .HasForeignKey("AccusedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Complainant")
                        .WithMany("ComplaintComplainants")
                        .HasForeignKey("ComplainantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("Complaints")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accused");

                    b.Navigation("Complainant");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CreditTransactionHistory", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Feedback", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewee")
                        .WithMany("FeedbackReviewees")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewer")
                        .WithMany("FeedbackReviewers")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Message", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Notification", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.OfferDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "CollectionOffer")
                        .WithMany("OfferDetails")
                        .HasForeignKey("CollectionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany()
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionOffer");

                    b.Navigation("ScrapCategory");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.PaymentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PointHistory", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Profile", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.Rank", "Rank")
                        .WithMany("Profiles")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ReferencePrice", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany()
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScheduleProposal", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "Offer")
                        .WithMany("ScheduleProposals")
                        .HasForeignKey("CollectionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Proposer")
                        .WithMany("ScheduleProposals")
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Proposer");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Household")
                        .WithMany("ScrapPosts")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPostDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany("ScrapPostDetails")
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapPost", "ScrapPost")
                        .WithMany("ScrapPostDetails")
                        .HasForeignKey("ScrapPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("ScrapPost");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Household")
                        .WithMany("TransactionHouseholds")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "Offer")
                        .WithMany("Transactions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "ScrapCollector")
                        .WithMany("TransactionScrapCollectors")
                        .HasForeignKey("ScrapCollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Offer");

                    b.Navigation("ScrapCollector");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.TransactionDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserDevice", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserPackage", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.PaymentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserRewardRedemption", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.RewardItem", "RewardItem")
                        .WithMany("UserRewardRedemptions")
                        .HasForeignKey("RewardItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany("UserRewardRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.Navigation("OfferDetails");

                    b.Navigation("ScheduleProposals");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Rank", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.RewardItem", b =>
                {
                    b.Navigation("UserRewardRedemptions");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapCategory", b =>
                {
                    b.Navigation("ScrapPostDetails");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.Navigation("CollectionOffers");

                    b.Navigation("ScrapPostDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.Navigation("ChatRoom");

                    b.Navigation("Complaints");

                    b.Navigation("Feedbacks");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.User", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("CollectionOffers");

                    b.Navigation("CollectorVerificationInfo");

                    b.Navigation("ComplaintAccuseds");

                    b.Navigation("ComplaintComplainants");

                    b.Navigation("FeedbackReviewees");

                    b.Navigation("FeedbackReviewers");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("ScheduleProposals");

                    b.Navigation("ScrapPosts");

                    b.Navigation("TransactionHouseholds");

                    b.Navigation("TransactionScrapCollectors");

                    b.Navigation("UserRewardRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
