// <auto-generated />
using System;
using GreenConnectPlatform.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenConnectPlatform.Data.Migrations
{
    [DbContext(typeof(GreenConnectDbContext))]
    partial class GreenConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatParticipant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "ChatRoomId")
                        .HasName("ChatParticipants_pkey");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatParticipants");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            ChatRoomId = new Guid("50000000-0000-0000-0000-000000000001"),
                            JoinedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ChatRoomId = new Guid("50000000-0000-0000-0000-000000000001"),
                            JoinedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId")
                        .HasName("ChatRooms_pkey");

                    b.HasIndex(new[] { "TransactionId" }, "ChatRooms_TransactionId_key")
                        .IsUnique();

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            ChatRoomId = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ScrapCollectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CollectionOfferId")
                        .HasName("CollectionOffers_pkey");

                    b.HasIndex("ScrapCollectorId");

                    b.HasIndex("ScrapPostId");

                    b.ToTable("CollectionOffers");

                    b.HasData(
                        new
                        {
                            CollectionOfferId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Status = 1
                        },
                        new
                        {
                            CollectionOfferId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentBackUrl")
                        .HasColumnType("text");

                    b.Property<string>("DocumentFrontUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId")
                        .HasName("CollectorVerificationInfos_pkey");

                    b.HasIndex("ReviewerId");

                    b.ToTable("CollectorVerificationInfos");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            DocumentBackUrl = "https://example.com/images/anh_ba_cccd_sau.png",
                            DocumentFrontUrl = "https://example.com/images/anh_ba_cccd_truoc.png",
                            Status = "PendingReview",
                            SubmittedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            DocumentFrontUrl = "https://example.com/images/vua_abc_gpkd.png",
                            ReviewedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReviewerId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            ReviewerNotes = "Vựa uy tín, đã xác nhận.",
                            Status = "Approved",
                            SubmittedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccusedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplainantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ComplaintId")
                        .HasName("Complaints_pkey");

                    b.HasIndex("AccusedId");

                    b.HasIndex("ComplainantId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ComplaintId = new Guid("22222222-0000-0000-0000-000000000001"),
                            AccusedId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ComplainantId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            CreatedAt = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Vựa tới nơi trả giá ép giá, không đúng thỏa thuận!",
                            Status = "Submitted",
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("FeedbackId")
                        .HasName("Feedbacks_pkey");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = new Guid("44444444-0000-0000-0000-000000000001"),
                            Comment = "Vựa thu gom nhanh, cân đo chính xác!",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Rate = 5,
                            RevieweeId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ReviewerId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId")
                        .HasName("Messages_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ChatRoomId", "Timestamp" }, "IX_Messages_ChatRoomId_Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = new Guid("88888888-0000-0000-0000-000000000001"),
                            ChatRoomId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Content = "Chào chị, em là bên Vựa ABC, em qua thu gom theo lịch hẹn nhé.",
                            IsRead = false,
                            SenderId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Timestamp = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MessageId = new Guid("88888888-0000-0000-0000-000000000002"),
                            ChatRoomId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Content = "OK bạn, mình ở nhà.",
                            IsRead = false,
                            SenderId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Timestamp = new DateTime(2025, 10, 10, 13, 1, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId")
                        .HasName("Notifications_pkey");

                    b.HasIndex(new[] { "RecipientId", "CreatedAt" }, "IX_Notifications_RecipientId_CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = new Guid("12121212-0000-0000-0000-000000000001"),
                            Content = "Vựa Ve Chai ABC đã gửi đề nghị thu gom cho bài đăng 'Dọn nhà bếp...'",
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("30000000-0000-0000-0000-000000000001"),
                            EntityType = "Offer",
                            IsRead = false,
                            RecipientId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.OfferDetail", b =>
                {
                    b.Property<Guid>("OfferDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("kg");

                    b.HasKey("OfferDetailId");

                    b.HasIndex("CollectionOfferId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("OfferDetail");

                    b.HasData(
                        new
                        {
                            OfferDetailId = new Guid("33333333-0000-0000-0000-000000000001"),
                            CollectionOfferId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PricePerUnit = 3000m,
                            ScrapCategoryId = 3,
                            Unit = "kg"
                        },
                        new
                        {
                            OfferDetailId = new Guid("33333333-0000-0000-0000-000000000002"),
                            CollectionOfferId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PricePerUnit = 25000m,
                            ScrapCategoryId = 4,
                            Unit = "kg"
                        },
                        new
                        {
                            OfferDetailId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CollectionOfferId = new Guid("30000000-0000-0000-0000-000000000002"),
                            PricePerUnit = 50000m,
                            ScrapCategoryId = 6,
                            Unit = "cái"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConnectionAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PackageType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("PackageId");

                    b.ToTable("PaymentPackages");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            ConnectionAmount = 5,
                            Description = "Gói miễn phí cho người dùng mới trải nghiệm.",
                            IsActive = true,
                            Name = "Gói Dùng Thử",
                            PackageType = 0,
                            Price = 0m
                        },
                        new
                        {
                            PackageId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            Description = "Kết nối không giới hạn trong 30 ngày.",
                            IsActive = true,
                            Name = "Gói Chuyên Nghiệp (1 Tháng)",
                            PackageType = 1,
                            Price = 99000m
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PaymentId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("77777777-0000-0000-0000-000000000001"),
                            Amount = 99000m,
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            PaymentGateway = "VNPay",
                            Status = 1,
                            TransactionCode = "VNP123456",
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PointHistory", b =>
                {
                    b.Property<Guid>("PointHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PointHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("PointHistories");

                    b.HasData(
                        new
                        {
                            PointHistoryId = new Guid("55555555-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = 50,
                            Reason = "Completed Transaction #40000000",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            PointHistoryId = new Guid("55555555-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = 50,
                            Reason = "Completed Transaction #40000000",
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        },
                        new
                        {
                            PointHistoryId = new Guid("99999999-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = -100,
                            Reason = "Redeemed 'Khung viền Avatar'",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            PointHistoryId = new Guid("33333333-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = -100,
                            Reason = "Submitted Complaint",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<int>("PointBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(200);

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileId")
                        .HasName("Profiles_pkey");

                    b.HasIndex("RankId");

                    b.HasIndex(new[] { "Location" }, "IX_Profiles_Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Location" }, "IX_Profiles_Location"), "gist");

                    b.HasIndex(new[] { "UserId" }, "Profiles_UserId_key")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Address = "123 Admin St, District 1, HCMC",
                            PointBalance = 200,
                            RankId = 1,
                            UserId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ProfileId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Address = "456 Collector Rd, Binh Thanh, HCMC",
                            Gender = "Male",
                            PointBalance = 200,
                            RankId = 1,
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00")
                        },
                        new
                        {
                            ProfileId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Address = "789 Household Ave, District 3, HCMC",
                            Gender = "Female",
                            PointBalance = 200,
                            RankId = 1,
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            ProfileId = new Guid("22222222-0000-0000-0000-000000000004"),
                            Address = "100 Vua Ve Chai St, District 10, HCMC",
                            PointBalance = 6000,
                            RankId = 2,
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankId"));

                    b.Property<string>("BadgeImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RankId");

                    b.HasIndex("MinPoints")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            RankId = 1,
                            BadgeImageUrl = "/images/badges/bronze.png",
                            MinPoints = 0,
                            Name = "Bronze"
                        },
                        new
                        {
                            RankId = 2,
                            BadgeImageUrl = "/images/badges/silver.png",
                            MinPoints = 5000,
                            Name = "Silver"
                        },
                        new
                        {
                            RankId = 3,
                            BadgeImageUrl = "/images/badges/gold.png",
                            MinPoints = 20000,
                            Name = "Gold"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ReferencePrice", b =>
                {
                    b.Property<Guid>("ReferencePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferencePriceId");

                    b.HasIndex("ScrapCategoryId");

                    b.HasIndex("UpdatedByAdminId");

                    b.ToTable("ReferencePrices");

                    b.HasData(
                        new
                        {
                            ReferencePriceId = new Guid("11111111-0000-0000-0000-000000000001"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 3000m,
                            ScrapCategoryId = 3,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("11111111-0000-0000-0000-000000000002"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 25000m,
                            ScrapCategoryId = 4,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.RewardItem", b =>
                {
                    b.Property<int>("RewardItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RewardItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("integer");

                    b.HasKey("RewardItemId")
                        .HasName("RewardItems_pkey");

                    b.ToTable("RewardItems");

                    b.HasData(
                        new
                        {
                            RewardItemId = 1,
                            ItemName = "Khung viền Avatar 'Chiến binh Tái chế'",
                            PointsCost = 100
                        },
                        new
                        {
                            RewardItemId = 2,
                            ItemName = "Voucher Giảm giá 10% (fake)",
                            PointsCost = 500
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScheduleProposal", b =>
                {
                    b.Property<Guid>("ScheduleProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ProposedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleProposalId")
                        .HasName("ScheduleProposals_pkey");

                    b.HasIndex("ProposerId");

                    b.HasIndex(new[] { "TransactionId" }, "IX_ScheduleProposals_TransactionId");

                    b.ToTable("ScheduleProposals");

                    b.HasData(
                        new
                        {
                            ScheduleProposalId = new Guid("13131313-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProposedTime = new DateTime(2025, 10, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProposerId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Status = "Accepted",
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapCategory", b =>
                {
                    b.Property<int>("ScrapCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScrapCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ScrapCategoryId")
                        .HasName("ScrapCategories_pkey");

                    b.ToTable("ScrapCategories");

                    b.HasData(
                        new
                        {
                            ScrapCategoryId = 1,
                            CategoryName = "Giấy vụn"
                        },
                        new
                        {
                            ScrapCategoryId = 2,
                            CategoryName = "Thùng carton"
                        },
                        new
                        {
                            ScrapCategoryId = 3,
                            CategoryName = "Chai nhựa (PET)"
                        },
                        new
                        {
                            ScrapCategoryId = 4,
                            CategoryName = "Lon nhôm"
                        },
                        new
                        {
                            ScrapCategoryId = 5,
                            CategoryName = "Sắt vụn"
                        },
                        new
                        {
                            ScrapCategoryId = 6,
                            CategoryName = "Đồ điện tử cũ"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvailableTimeRange")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<bool>("MustTakeAll")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScrapPostId")
                        .HasName("ScrapPosts_pkey");

                    b.HasIndex("HouseholdId");

                    b.HasIndex(new[] { "Location" }, "IX_ScrapPosts_Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Location" }, "IX_ScrapPosts_Location"), "gist");

                    b.HasIndex(new[] { "Status", "HouseholdId" }, "IX_ScrapPosts_Status_HouseholdId");

                    b.ToTable("ScrapPosts");

                    b.HasData(
                        new
                        {
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Address = "789 Household Ave, District 3, HCMC",
                            AvailableTimeRange = "Chiều nay (14h-16h)",
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khoảng 1 bao lớn, đã gom sạch sẽ.",
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            MustTakeAll = false,
                            Status = 3,
                            Title = "Dọn nhà bếp, có chai nhựa và lon"
                        },
                        new
                        {
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Address = "456 Collector Rd, Binh Thanh, HCMC",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            MustTakeAll = false,
                            Status = 3,
                            Title = "Đồ điện tử cũ"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPostDetail", b =>
                {
                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("AmountDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScrapPostId", "ScrapCategoryId")
                        .HasName("ScrapPostDetails_pkey");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("ScrapPostDetails");

                    b.HasData(
                        new
                        {
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 3,
                            AmountDescription = "Khoảng 1 bao lớn",
                            Status = "Collected"
                        },
                        new
                        {
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 4,
                            AmountDescription = "Khoảng 50 lon",
                            Status = "Collected"
                        },
                        new
                        {
                            ScrapPostId = new Guid("20000000-0000-0000-0000-000000000003"),
                            ScrapCategoryId = 6,
                            AmountDescription = "1 cái TV hỏng",
                            Status = "Collected"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScrapCollectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId")
                        .HasName("Transactions_pkey");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ScrapCollectorId");

                    b.HasIndex(new[] { "Status", "HouseholdId" }, "IX_Transactions_Status_HouseholdId");

                    b.HasIndex(new[] { "Status", "ScrapCollectorId" }, "IX_Transactions_Status_ScrapCollectorId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000001"),
                            CheckInTime = new DateTime(2025, 10, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            OfferId = new Guid("30000000-0000-0000-0000-000000000001"),
                            ScheduledTime = new DateTime(2025, 10, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Status = "Completed"
                        },
                        new
                        {
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            OfferId = new Guid("30000000-0000-0000-0000-000000000002"),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.TransactionDetail", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("kg");

                    b.HasKey("TransactionId", "ScrapCategoryId")
                        .HasName("TransactionDetails_pkey");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("TransactionDetails");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 3,
                            FinalPrice = 15000m,
                            PricePerUnit = 3000m,
                            Quantity = 5f,
                            Unit = "kg"
                        },
                        new
                        {
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 4,
                            FinalPrice = 35000m,
                            PricePerUnit = 25000m,
                            Quantity = 1.4f,
                            Unit = "kg"
                        },
                        new
                        {
                            TransactionId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ScrapCategoryId = 6,
                            FinalPrice = 50000m,
                            PricePerUnit = 50000m,
                            Quantity = 1f,
                            Unit = "cái"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BuyerType")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f1752c1-c363-46b6-9d3b-852257040f73",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Admin GreenConnect",
                            LockoutEnabled = false,
                            NormalizedUserName = "0900000000",
                            PasswordHash = "AQAAAAIAAYagAAAAEDmdqqVjPEcGnYT3hugAntBzyIN2dWsejrKbiqciN/LzWhifHV6aiV58TKe3h5J5Hg==",
                            PhoneNumber = "0900000000",
                            PhoneNumberConfirmed = true,
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "0900000000"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            AccessFailedCount = 0,
                            BuyerType = 0,
                            ConcurrencyStamp = "099ea22f-510e-447a-aebc-932d3901d82c",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            FullName = "Anh Ba Ve Chai",
                            LockoutEnabled = false,
                            NormalizedUserName = "0911111111",
                            PhoneNumber = "0911111111",
                            PhoneNumberConfirmed = true,
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "0911111111"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c9c59db-7840-41c7-98f0-2b44661f4a74",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            FullName = "Chị Tư Bán Ve Chai",
                            LockoutEnabled = false,
                            NormalizedUserName = "0922222222",
                            PhoneNumber = "0922222222",
                            PhoneNumberConfirmed = true,
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "0922222222"
                        },
                        new
                        {
                            Id = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            AccessFailedCount = 0,
                            BuyerType = 1,
                            ConcurrencyStamp = "9c2893bb-b992-4997-8132-bd0c0318cea7",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            FullName = "Vựa Ve Chai ABC",
                            LockoutEnabled = false,
                            NormalizedUserName = "0988888888",
                            PhoneNumber = "0988888888",
                            PhoneNumberConfirmed = true,
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "0988888888"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserPackage", b =>
                {
                    b.Property<Guid>("UserPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingConnections")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPackageId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPackages");

                    b.HasData(
                        new
                        {
                            UserPackageId = new Guid("66666666-0000-0000-0000-000000000001"),
                            ActivationDate = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            RemainingConnections = 5,
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00")
                        },
                        new
                        {
                            UserPackageId = new Guid("66666666-0000-0000-0000-000000000002"),
                            ActivationDate = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2025, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserRewardRedemption", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RedemptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RewardItemId", "RedemptionDate")
                        .HasName("UserRewardRedemptions_pkey");

                    b.HasIndex("RewardItemId");

                    b.ToTable("UserRewardRedemptions");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            RewardItemId = 1,
                            RedemptionDate = new DateTime(2025, 10, 10, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dd3637c-72a3-4a25-99d2-a7d1bce85542"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f9e7c1b5-9c8f-4b1a-8c7d-6e5f4a3b2a1c"),
                            Name = "Household",
                            NormalizedName = "HOUSEHOLD"
                        },
                        new
                        {
                            Id = new Guid("d7d0c75c-9c3f-4e6b-9b7a-8f8d9a6c9e84"),
                            Name = "IndividualCollector",
                            NormalizedName = "INDIVIDUALCOLLECTOR"
                        },
                        new
                        {
                            Id = new Guid("e0a5a415-5a4e-4f6a-8b9a-1b2c3d4e5f6a"),
                            Name = "BusinessCollector",
                            NormalizedName = "BUSINESSCOLLECTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            RoleId = new Guid("8dd3637c-72a3-4a25-99d2-a7d1bce85542")
                        },
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            RoleId = new Guid("f9e7c1b5-9c8f-4b1a-8c7d-6e5f4a3b2a1c")
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            RoleId = new Guid("d7d0c75c-9c3f-4e6b-9b7a-8f8d9a6c9e84")
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            RoleId = new Guid("e0a5a415-5a4e-4f6a-8b9a-1b2c3d4e5f6a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatParticipant", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatParticipants_ChatRoomId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatParticipants_UserId_fkey");

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithOne("ChatRoom")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.ChatRoom", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ChatRooms_TransactionId_fkey");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "ScrapCollector")
                        .WithMany("CollectionOffers")
                        .HasForeignKey("ScrapCollectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CollectionOffers_ScrapCollectorId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapPost", "ScrapPost")
                        .WithMany("CollectionOffers")
                        .HasForeignKey("ScrapPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CollectionOffers_ScrapPostId_fkey");

                    b.Navigation("ScrapCollector");

                    b.Navigation("ScrapPost");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithOne("CollectorVerificationInfo")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CollectorVerificationInfos_UserId_fkey");

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Complaint", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Accused")
                        .WithMany("ComplaintAccuseds")
                        .HasForeignKey("AccusedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Complaints_AccusedId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Complainant")
                        .WithMany("ComplaintComplainants")
                        .HasForeignKey("ComplainantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Complaints_ComplainantId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("Complaints")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Complaints_TransactionId_fkey");

                    b.Navigation("Accused");

                    b.Navigation("Complainant");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Feedback", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewee")
                        .WithMany("FeedbackReviewees")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Feedbacks_RevieweeId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewer")
                        .WithMany("FeedbackReviewers")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Feedbacks_ReviewerId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Feedbacks_TransactionId_fkey");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Message", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Messages_ChatRoomId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Messages_SenderId_fkey");

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Notification", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Notifications_RecipientId_fkey");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.OfferDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "CollectionOffer")
                        .WithMany("OfferDetails")
                        .HasForeignKey("CollectionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany()
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionOffer");

                    b.Navigation("ScrapCategory");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.PaymentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PointHistory", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Profile", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.Rank", "Rank")
                        .WithMany("Profiles")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Profiles_UserId_fkey");

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ReferencePrice", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany()
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScheduleProposal", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Proposer")
                        .WithMany("ScheduleProposals")
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ScheduleProposals_ProposerId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("ScheduleProposals")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ScheduleProposals_TransactionId_fkey");

                    b.Navigation("Proposer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Household")
                        .WithMany("ScrapPosts")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ScrapPosts_HouseholdId_fkey");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPostDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany("ScrapPostDetails")
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ScrapPostDetails_ScrapCategoryId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapPost", "ScrapPost")
                        .WithMany("ScrapPostDetails")
                        .HasForeignKey("ScrapPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ScrapPostDetails_ScrapPostId_fkey");

                    b.Navigation("ScrapCategory");

                    b.Navigation("ScrapPost");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Household")
                        .WithMany("TransactionHouseholds")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Transactions_HouseholdId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "Offer")
                        .WithMany("Transactions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Transactions_OfferId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "ScrapCollector")
                        .WithMany("TransactionScrapCollectors")
                        .HasForeignKey("ScrapCollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Transactions_ScrapCollectorId_fkey");

                    b.Navigation("Household");

                    b.Navigation("Offer");

                    b.Navigation("ScrapCollector");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.TransactionDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("TransactionDetails_ScrapCategoryId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TransactionDetails_TransactionId_fkey");

                    b.Navigation("ScrapCategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserPackage", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.PaymentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserRewardRedemption", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.RewardItem", "RewardItem")
                        .WithMany("UserRewardRedemptions")
                        .HasForeignKey("RewardItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserRewardRedemptions_RewardItemId_fkey");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany("UserRewardRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserRewardRedemptions_UserId_fkey");

                    b.Navigation("RewardItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.Navigation("OfferDetails");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Rank", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.RewardItem", b =>
                {
                    b.Navigation("UserRewardRedemptions");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapCategory", b =>
                {
                    b.Navigation("ScrapPostDetails");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.Navigation("CollectionOffers");

                    b.Navigation("ScrapPostDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.Navigation("ChatRoom");

                    b.Navigation("Complaints");

                    b.Navigation("Feedbacks");

                    b.Navigation("ScheduleProposals");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.User", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("CollectionOffers");

                    b.Navigation("CollectorVerificationInfo");

                    b.Navigation("ComplaintAccuseds");

                    b.Navigation("ComplaintComplainants");

                    b.Navigation("FeedbackReviewees");

                    b.Navigation("FeedbackReviewers");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("ScheduleProposals");

                    b.Navigation("ScrapPosts");

                    b.Navigation("TransactionHouseholds");

                    b.Navigation("TransactionScrapCollectors");

                    b.Navigation("UserRewardRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
