// <auto-generated />
using System;
using GreenConnectPlatform.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenConnectPlatform.Data.Migrations
{
    [DbContext(typeof(GreenConnectDbContext))]
    partial class GreenConnectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatParticipant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "ChatRoomId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("ChatParticipants");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            ChatRoomId = new Guid("98f753e3-4bd6-4030-9f2c-f7f219c580a8"),
                            JoinedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ChatRoomId = new Guid("98f753e3-4bd6-4030-9f2c-f7f219c580a8"),
                            JoinedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            ChatRoomId = new Guid("98f753e3-4bd6-4030-9f2c-f7f219c580a8"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScrapCollectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CollectionOfferId");

                    b.HasIndex("ScrapCollectorId");

                    b.HasIndex("ScrapPostId");

                    b.ToTable("CollectionOffers");

                    b.HasData(
                        new
                        {
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentBackUrl")
                        .HasColumnType("text");

                    b.Property<string>("DocumentFrontUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("CollectorVerificationInfos");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            DocumentBackUrl = "back.jpg",
                            DocumentFrontUrl = "front.jpg",
                            Status = "PendingReview",
                            SubmittedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            DocumentFrontUrl = "license.jpg",
                            ReviewedAt = new DateTime(2025, 10, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReviewerId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            Status = "Approved",
                            SubmittedAt = new DateTime(2025, 9, 30, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Complaint", b =>
                {
                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccusedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplainantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ComplaintId");

                    b.HasIndex("AccusedId");

                    b.HasIndex("ComplainantId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ComplaintId = new Guid("300392cc-e1d0-41fe-8c9d-692cb505f506"),
                            AccusedId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            ComplainantId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Hẹn không đến.",
                            Status = "Submitted",
                            TransactionId = new Guid("70000002-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CreditTransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditTransactionHistory");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("FeedbackId");

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = new Guid("1e93bb8f-61bf-420e-82ea-14983375e7d4"),
                            Comment = "Nhanh gọn lẹ.",
                            CreatedAt = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            Rate = 5,
                            RevieweeId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ReviewerId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ChatRoomId", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = new Guid("675158cb-649c-4912-aa3b-f8d6f2707bc0"),
                            ChatRoomId = new Guid("98f753e3-4bd6-4030-9f2c-f7f219c580a8"),
                            Content = "Chào chị, em tới rồi.",
                            IsRead = true,
                            SenderId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Timestamp = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MessageId = new Guid("b9997598-322d-4c9e-b176-858f4c135a41"),
                            ChatRoomId = new Guid("98f753e3-4bd6-4030-9f2c-f7f219c580a8"),
                            Content = "Ok em.",
                            IsRead = true,
                            SenderId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Timestamp = new DateTime(2025, 10, 10, 12, 1, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationId");

                    b.HasIndex("RecipientId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = new Guid("44cb32e4-16da-4853-a2df-95c487d61cd7"),
                            Content = "Vựa ABC đã hoàn thành đơn hàng.",
                            CreatedAt = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            EntityId = new Guid("70000001-0000-0000-0000-000000000001"),
                            EntityType = "Transaction",
                            IsRead = false,
                            RecipientId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.OfferDetail", b =>
                {
                    b.Property<Guid>("OfferDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("kg");

                    b.HasKey("OfferDetailId");

                    b.HasIndex("CollectionOfferId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("OfferDetail");

                    b.HasData(
                        new
                        {
                            OfferDetailId = new Guid("ee5adde4-88de-4334-b6eb-00c01536aad3"),
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            PricePerUnit = 3000m,
                            ScrapCategoryId = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            OfferDetailId = new Guid("c52875f4-70ad-4cc3-8c6b-2ef8a4d6205e"),
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            PricePerUnit = 5000m,
                            ScrapCategoryId = 2,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentPackage", b =>
                {
                    b.Property<Guid>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ConnectionAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("PackageId");

                    b.ToTable("PaymentPackages");

                    b.HasData(
                        new
                        {
                            PackageId = new Guid("a1111111-0000-0000-0000-000000000001"),
                            ConnectionAmount = 5,
                            Description = "5 lượt/tuần",
                            IsActive = true,
                            Name = "Gói Free",
                            PackageType = "Freemium",
                            Price = 0m
                        },
                        new
                        {
                            PackageId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            ConnectionAmount = 500,
                            Description = "500 lượt/tháng",
                            IsActive = true,
                            Name = "Gói Pro",
                            PackageType = "Paid",
                            Price = 200000m
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankCode")
                        .HasColumnType("text");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderInfo")
                        .HasColumnType("text");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VnpTransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("a8909d9e-9113-42d1-bc22-5360180e632b"),
                            Amount = 200000m,
                            BankCode = "NCB",
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderInfo = "Mua Goi Pro",
                            PackageId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            PaymentGateway = "VNPay",
                            ResponseCode = "00",
                            Status = "Success",
                            TransactionRef = "ORD001",
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            VnpTransactionNo = "VNP001"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PointHistory", b =>
                {
                    b.Property<Guid>("PointHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("PointHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("PointHistories");

                    b.HasData(
                        new
                        {
                            PointHistoryId = new Guid("7ac402ab-f0ba-4a4f-9623-9761e7fa162e"),
                            CreatedAt = new DateTime(2025, 10, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = 10,
                            Reason = "Hoàn thành đơn",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            PointHistoryId = new Guid("4cf6bbbc-1332-4876-b705-95aa43f52c3a"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            PointChange = -20,
                            Reason = "Khiếu nại",
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CreditBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<int>("PointBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(200);

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            ProfileId = new Guid("5af913b5-6f87-488c-b0ec-7a34bc9dca6b"),
                            Address = "Headquarter",
                            CreditBalance = 0,
                            PointBalance = 9999,
                            RankId = 3,
                            UserId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ProfileId = new Guid("ae90516c-bf6b-4c3c-b9b6-e662ba414812"),
                            Address = "123 CMT8, Q3, HCM",
                            BankAccountName = "NGUYEN THI TU",
                            BankAccountNumber = "0922222222",
                            BankCode = "970422",
                            CreditBalance = 0,
                            Gender = "Female",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            PointBalance = 50,
                            RankId = 1,
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011")
                        },
                        new
                        {
                            ProfileId = new Guid("984825fb-8e1d-42d9-b18e-f0c10fbed485"),
                            Address = "Hẻm 456 Lê Văn Sỹ, Q3, HCM",
                            CreditBalance = 0,
                            Gender = "Male",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.68 10.78)"),
                            PointBalance = 120,
                            RankId = 1,
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00")
                        },
                        new
                        {
                            ProfileId = new Guid("f1a2ca59-0a02-4ffa-b35f-5a880351004b"),
                            Address = "Kho Quận 7, HCM",
                            BankAccountName = "CTY ABC",
                            BankAccountNumber = "0988888888",
                            BankCode = "970436",
                            CreditBalance = 0,
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.72 10.75)"),
                            PointBalance = 5000,
                            RankId = 2,
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RankId"));

                    b.Property<string>("BadgeImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RankId");

                    b.HasIndex("MinPoints")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            RankId = 1,
                            BadgeImageUrl = "bronze.png",
                            MinPoints = 0,
                            Name = "Mới"
                        },
                        new
                        {
                            RankId = 2,
                            BadgeImageUrl = "silver.png",
                            MinPoints = 1000,
                            Name = "Bạc"
                        },
                        new
                        {
                            RankId = 3,
                            BadgeImageUrl = "gold.png",
                            MinPoints = 5000,
                            Name = "Vàng"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ReferencePrice", b =>
                {
                    b.Property<Guid>("ReferencePriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferencePriceId");

                    b.HasIndex("ScrapCategoryId");

                    b.HasIndex("UpdatedByAdminId");

                    b.ToTable("ReferencePrices");

                    b.HasData(
                        new
                        {
                            ReferencePriceId = new Guid("4977f38e-b859-4ce8-bc09-30af002e4fae"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 3000m,
                            ScrapCategoryId = 1,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("199b8d36-35fd-4e08-bb66-6b8179a868d2"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 5000m,
                            ScrapCategoryId = 2,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("0a629df4-ed47-48e3-804f-d94f11228c45"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 15000m,
                            ScrapCategoryId = 3,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        },
                        new
                        {
                            ReferencePriceId = new Guid("bad9450b-ee58-45d4-954f-8166f540bee7"),
                            LastUpdated = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PricePerKg = 8000m,
                            ScrapCategoryId = 4,
                            UpdatedByAdminId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.RewardItem", b =>
                {
                    b.Property<int>("RewardItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RewardItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RewardItemId");

                    b.ToTable("RewardItems");

                    b.HasData(
                        new
                        {
                            RewardItemId = 1,
                            Description = "Đổi ngay 1 lượt xem SĐT để liên hệ chủ bài đăng.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_credit_1.png",
                            ItemName = "1 Lượt Kết Nối",
                            PointsCost = 100,
                            Type = "Credit",
                            Value = "1"
                        },
                        new
                        {
                            RewardItemId = 2,
                            Description = "Gói tiết kiệm. Phù hợp cho người thu gom thường xuyên.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_credit_5.png",
                            ItemName = "Combo 5 Lượt",
                            PointsCost = 450,
                            Type = "Credit",
                            Value = "5"
                        },
                        new
                        {
                            RewardItemId = 3,
                            Description = "Gói sỉ siêu hời. Thoải mái kết nối.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_credit_10.png",
                            ItemName = "Combo 10 Lượt",
                            PointsCost = 800,
                            Type = "Credit",
                            Value = "10"
                        },
                        new
                        {
                            RewardItemId = 4,
                            Description = "Mở khóa không giới hạn lượt xem và tính năng Pro trong 24h.",
                            ImageUrl = "https://firebasestorage.googleapis.com/.../icon_vip_day.png",
                            ItemName = "Dùng thử VIP 1 Ngày",
                            PointsCost = 2000,
                            Type = "Package",
                            Value = "a2222222-0000-0000-0000-000000000001|1"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScheduleProposal", b =>
                {
                    b.Property<Guid>("ScheduleProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionOfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProposedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScheduleProposalId");

                    b.HasIndex("CollectionOfferId");

                    b.HasIndex("ProposerId");

                    b.ToTable("ScheduleProposals");

                    b.HasData(
                        new
                        {
                            ScheduleProposalId = new Guid("2bb38ccc-db21-49cc-ac67-9bbd0c2aa217"),
                            CollectionOfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 10, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProposedTime = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProposerId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            ResponseMessage = "Ok chốt",
                            Status = "Accepted"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapCategory", b =>
                {
                    b.Property<int>("ScrapCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScrapCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("ScrapCategoryId");

                    b.ToTable("ScrapCategories");

                    b.HasData(
                        new
                        {
                            ScrapCategoryId = 1,
                            CategoryName = "Giấy / Carton"
                        },
                        new
                        {
                            ScrapCategoryId = 2,
                            CategoryName = "Nhựa (Chai/Lọ)"
                        },
                        new
                        {
                            ScrapCategoryId = 3,
                            CategoryName = "Lon Nhôm"
                        },
                        new
                        {
                            ScrapCategoryId = 4,
                            CategoryName = "Sắt vụn"
                        },
                        new
                        {
                            ScrapCategoryId = 5,
                            CategoryName = "Đồ điện tử"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvailableTimeRange")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<bool>("MustTakeAll")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScrapPostId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Status", "HouseholdId");

                    b.ToTable("ScrapPosts");

                    b.HasData(
                        new
                        {
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Address = "123 CMT8",
                            CreatedAt = new DateTime(2025, 10, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lấy hết giúp em.",
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            MustTakeAll = true,
                            Status = "Completed",
                            Title = "Dọn kho Giấy & Nhựa"
                        },
                        new
                        {
                            ScrapPostId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            Address = "123 CMT8",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ai tiện ghé lấy.",
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            MustTakeAll = false,
                            Status = "Open",
                            Title = "Bán 50 vỏ lon"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPostDetail", b =>
                {
                    b.Property<Guid>("ScrapPostId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("AmountDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScrapPostId", "ScrapCategoryId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("ScrapPostDetails");

                    b.HasData(
                        new
                        {
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 1,
                            AmountDescription = "20kg",
                            Status = "Collected"
                        },
                        new
                        {
                            ScrapPostId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 2,
                            AmountDescription = "2 bao",
                            Status = "Collected"
                        },
                        new
                        {
                            ScrapPostId = new Guid("b0000002-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 3,
                            AmountDescription = "50 lon",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Point>("CheckInLocation")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScrapCollectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ScrapCollectorId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001"),
                            CheckInLocation = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (106.69 10.777)"),
                            CheckInTime = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 3, 18, 25, 33, 125, DateTimeKind.Utc).AddTicks(5972),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            OfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            PaymentMethod = "Cash",
                            ScheduledTime = new DateTime(2025, 10, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            ScrapCollectorId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            Status = "Completed",
                            TotalAmount = 100000m
                        },
                        new
                        {
                            TransactionId = new Guid("70000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            HouseholdId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            OfferId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            ScrapCollectorId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            Status = "CanceledByUser",
                            TotalAmount = 0m
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.TransactionDetail", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScrapCategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("kg");

                    b.HasKey("TransactionId", "ScrapCategoryId");

                    b.HasIndex("ScrapCategoryId");

                    b.ToTable("TransactionDetails");

                    b.HasData(
                        new
                        {
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 1,
                            FinalPrice = 45000m,
                            PricePerUnit = 3000m,
                            Quantity = 15f,
                            Unit = "kg"
                        },
                        new
                        {
                            TransactionId = new Guid("70000001-0000-0000-0000-000000000001"),
                            ScrapCategoryId = 2,
                            FinalPrice = 55000m,
                            PricePerUnit = 5000m,
                            Quantity = 11f,
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BuyerType")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e973a08-46bc-4f86-914a-fb5d31b3ac08",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gc.com",
                            EmailConfirmed = true,
                            FullName = "Admin System",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GC.COM",
                            NormalizedUserName = "0900000000",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0900000000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "7e0de5c2-2a83-4730-8df8-9a34377d753a",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0900000000"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d3e670e1-e669-4400-86d3-23b0421f8baf",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "chitu@gc.com",
                            EmailConfirmed = true,
                            FullName = "Chị Tư Nội Trợ",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHITU@GC.COM",
                            NormalizedUserName = "0922222222",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0922222222",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "311cb207-e89c-4094-af75-04f34d004a26",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0922222222"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            AccessFailedCount = 0,
                            BuyerType = "Individual",
                            ConcurrencyStamp = "5faaa3cf-f604-47ae-ab09-106a1e1046e8",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anhba@gc.com",
                            EmailConfirmed = true,
                            FullName = "Anh Ba Ve Chai",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANHBA@GC.COM",
                            NormalizedUserName = "0933333333",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0933333333",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "5111c008-028c-4724-8ba8-fbb5a5684a24",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0933333333"
                        },
                        new
                        {
                            Id = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            AccessFailedCount = 0,
                            BuyerType = "Business",
                            ConcurrencyStamp = "7a9b8462-fa7d-4114-a0fa-981f6e8959c0",
                            CreatedAt = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuaabc@gc.com",
                            EmailConfirmed = true,
                            FullName = "Vựa Tái Chế ABC",
                            LockoutEnabled = false,
                            NormalizedEmail = "VUAABC@GC.COM",
                            NormalizedUserName = "0988888888",
                            PasswordHash = "AQAAAAIAAYagAAAAELSd8S1/ERD0+I4lEAStNTTw/VOGuVVH8vE3SL92wYldv4i4XV78koh+GJ3GpdR05A==",
                            PhoneNumber = "0988888888",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a3086c36-089d-4161-b110-f468a746562f",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "0988888888"
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DeviceId");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserPackage", b =>
                {
                    b.Property<Guid>("UserPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RemainingConnections")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserPackageId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPackages");

                    b.HasData(
                        new
                        {
                            UserPackageId = new Guid("07b2bd88-53c9-46fd-afe1-6afa165799c6"),
                            ActivationDate = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("a1111111-0000-0000-0000-000000000001"),
                            RemainingConnections = 5,
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00")
                        },
                        new
                        {
                            UserPackageId = new Guid("6ca8eb1e-6ba5-4ee0-99b8-fad863081aee"),
                            ActivationDate = new DateTime(2025, 10, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            ExpirationDate = new DateTime(2025, 11, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            PackageId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            RemainingConnections = 499,
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef")
                        });
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserRewardRedemption", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RewardItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RedemptionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RewardItemId", "RedemptionDate");

                    b.HasIndex("RewardItemId");

                    b.ToTable("UserRewardRedemptions");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            RewardItemId = 2,
                            RedemptionDate = new DateTime(2025, 10, 10, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dd3637c-72a3-4a25-99d2-a7d1bce85542"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f9e7c1b5-9c8f-4b1a-8c7d-6e5f4a3b2a1c"),
                            Name = "Household",
                            NormalizedName = "HOUSEHOLD"
                        },
                        new
                        {
                            Id = new Guid("d7d0c75c-9c3f-4e6b-9b7a-8f8d9a6c9e84"),
                            Name = "IndividualCollector",
                            NormalizedName = "INDIVIDUALCOLLECTOR"
                        },
                        new
                        {
                            Id = new Guid("e0a5a415-5a4e-4f6a-8b9a-1b2c3d4e5f6a"),
                            Name = "BusinessCollector",
                            NormalizedName = "BUSINESSCOLLECTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-7788-9900-aabbccddeeff"),
                            RoleId = new Guid("8dd3637c-72a3-4a25-99d2-a7d1bce85542")
                        },
                        new
                        {
                            UserId = new Guid("c3d4e5f6-a1b2-9900-1122-ccddeeff0011"),
                            RoleId = new Guid("f9e7c1b5-9c8f-4b1a-8c7d-6e5f4a3b2a1c")
                        },
                        new
                        {
                            UserId = new Guid("b2c3d4e5-f6a1-8899-0011-bbccddeeff00"),
                            RoleId = new Guid("d7d0c75c-9c3f-4e6b-9b7a-8f8d9a6c9e84")
                        },
                        new
                        {
                            UserId = new Guid("e6a1b2c3-d4e5-f6a7-8899-0011bbccdeef"),
                            RoleId = new Guid("e0a5a415-5a4e-4f6a-8b9a-1b2c3d4e5f6a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatParticipant", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithOne("ChatRoom")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.ChatRoom", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "ScrapCollector")
                        .WithMany("CollectionOffers")
                        .HasForeignKey("ScrapCollectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapPost", "ScrapPost")
                        .WithMany("CollectionOffers")
                        .HasForeignKey("ScrapPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapCollector");

                    b.Navigation("ScrapPost");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithOne("CollectorVerificationInfo")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.CollectorVerificationInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Complaint", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Accused")
                        .WithMany("ComplaintAccuseds")
                        .HasForeignKey("AccusedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Complainant")
                        .WithMany("ComplaintComplainants")
                        .HasForeignKey("ComplainantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("Complaints")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accused");

                    b.Navigation("Complainant");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CreditTransactionHistory", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Feedback", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewee")
                        .WithMany("FeedbackReviewees")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Reviewer")
                        .WithMany("FeedbackReviewers")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Message", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Notification", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.OfferDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "CollectionOffer")
                        .WithMany("OfferDetails")
                        .HasForeignKey("CollectionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany()
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionOffer");

                    b.Navigation("ScrapCategory");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.PaymentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId");

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.PointHistory", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Profile", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.Rank", "Rank")
                        .WithMany("Profiles")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GreenConnectPlatform.Data.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ReferencePrice", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany()
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScheduleProposal", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "Offer")
                        .WithMany("ScheduleProposals")
                        .HasForeignKey("CollectionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Proposer")
                        .WithMany("ScheduleProposals")
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Proposer");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Household")
                        .WithMany("ScrapPosts")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPostDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany("ScrapPostDetails")
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapPost", "ScrapPost")
                        .WithMany("ScrapPostDetails")
                        .HasForeignKey("ScrapPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("ScrapPost");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "Household")
                        .WithMany("TransactionHouseholds")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.CollectionOffer", "Offer")
                        .WithMany("Transactions")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "ScrapCollector")
                        .WithMany("TransactionScrapCollectors")
                        .HasForeignKey("ScrapCollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Offer");

                    b.Navigation("ScrapCollector");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.TransactionDetail", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.ScrapCategory", "ScrapCategory")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("ScrapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.Transaction", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapCategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserDevice", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserPackage", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.PaymentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.UserRewardRedemption", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.RewardItem", "RewardItem")
                        .WithMany("UserRewardRedemptions")
                        .HasForeignKey("RewardItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", "User")
                        .WithMany("UserRewardRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GreenConnectPlatform.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ChatRoom", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.CollectionOffer", b =>
                {
                    b.Navigation("OfferDetails");

                    b.Navigation("ScheduleProposals");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Rank", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.RewardItem", b =>
                {
                    b.Navigation("UserRewardRedemptions");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapCategory", b =>
                {
                    b.Navigation("ScrapPostDetails");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.ScrapPost", b =>
                {
                    b.Navigation("CollectionOffers");

                    b.Navigation("ScrapPostDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.Transaction", b =>
                {
                    b.Navigation("ChatRoom");

                    b.Navigation("Complaints");

                    b.Navigation("Feedbacks");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("GreenConnectPlatform.Data.Entities.User", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("CollectionOffers");

                    b.Navigation("CollectorVerificationInfo");

                    b.Navigation("ComplaintAccuseds");

                    b.Navigation("ComplaintComplainants");

                    b.Navigation("FeedbackReviewees");

                    b.Navigation("FeedbackReviewers");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("ScheduleProposals");

                    b.Navigation("ScrapPosts");

                    b.Navigation("TransactionHouseholds");

                    b.Navigation("TransactionScrapCollectors");

                    b.Navigation("UserRewardRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
